### ISSUE TITLE
Why are CODECOV_* environment variables are not being passed through?

### ISSUE THREAD

**Issue by marcosschroh** [tox-dev/tox-travis#106]
Hi,

I have a question regarding environment variables used in `[commands]`

I am using travis, I have created a custom tox.ini file and the idea is to upload the coverage with codecov

This is my `.travis.yml`:
```
language: python

python:
  - "2.7"
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox-travis

script: tox
```
and this is my `.tox.ini`:

```
[tox]
envlist = py27,py36

[travis]
python =
  2.7: py27
  3.6: py36

[testenv]
passenv = CI TRAVIS
deps =
  coverage
  codecov

commands =
  echo CODECOV_TOKEN
  coverage run --source=sound_downloader -m unittest discover
  coverage report -m
  codecov --token CODECOV_TOKEN
```
For some reason seems that `CODECOV_TOKEN` is empty. I have set the option "display value in build log" in travis and the variable is correct:

```
Setting environment variables from repository settings
$ export CODECOV_TOKEN=xxxxxxxxxxxxx
```
Any ideas?

Best regards,

Marcos.

**Comment by rpkilby** [comment]
I'm fairly certain this needs to be added to the `passenv` declaration.

**Comment by marcosschroh** [comment]
Hi @obestwalter,

Thanks for the reply. I can confirm that is working. Like you and @rpkilby said, the CODECOV_* need to be added to `passenv`. 

```
[testenv]
passenv = CI TRAVIS CODECOV_TOKEN
```

Also, my mistake was using the option `-t` instead of `-e` in commands:

WRONG WAY:
```
commands =
  coverage run --source=sound_downloader -m unittest discover
  coverage report -m
  codecov -e CODECOV_TOKEN
```

GOOD WAY
```
commands =
  coverage run --source=sound_downloader -m unittest discover
  coverage report -m
  codecov -e CODECOV_TOKEN
```

**Comment by obestwalter** [comment]
Glad that it works now @marcosschroh - getting a new workflow up and running when you have a lot of moving parts is always a pain.
