### ISSUE TITLE
Document that you can test envlist matching locally

### ISSUE THREAD

**Issue by rpkilby** [tox-dev/tox-travis#122]
It might be useful to document in the env detection section that users can debug/test tox-travis's envlist matching by setting the appropriate CI environment variables. 

e.g., `TRAVIS=yes TRAVIS_PYTHON_VERSION=3.7 tox -l` will list of all matching `py37` test envs. 
```
py37-django20
py37-django21
py37-django22
```
yay/nay?

**Comment by ryanhiebert** [comment]
Yeah, that's fine with me. I was going to suggest adding a note that this isn't part of _our_ interface, so if we change that it won't be a breaking change, but I think a change is unlikely enough that I'm not too worried about it.

**Comment by blueyed** [comment]
Would be nice indeed, and should also be in the README then also - to help people that come there from trying to understand how tox-travis' magic works quickly.

**Comment by jayvdb** [comment]
Please document it using `TRAVIS=true` rather than `TRAVIS=yes`

And I think this isnt working on the latest tox, probably due to the bug already raised, so that needs fixing first.
