### ISSUE TITLE
Incompatible with parallel mode

### ISSUE THREAD

**Issue by rpkilby** [tox-dev/tox-travis#127]
Hi @ryanhiebert. I've been working on tox-factor, which is a stripped down version of tox-travis's envlist matching feature (e.g. invoked as `tox -f py37` to match all `py37-*` testenvs, instead of matching from Travis environment factors).

Anyway, like tox-travis, tox-factor ultimately works by setting the `config.envlist` in the `tox_configure` hook. However, this overrides the parallelized tox subprocesses, which have their testenv set via the `TOX_PARALLEL_ENV` env var. The fix is to ensure env matching only performs in the main tox process, not the parallelized subprocesses. For reference:
- original issue: rpkilby/tox-factor#3
- pull request: rpkilby/tox-factor#4
- tox parallel testing issue: tox-dev/tox#1275

**Comment by ryanhiebert** [comment]
Thanks! I've been wondering how that project was going.
