### ISSUE TITLE
Update link in description

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox-travis#145]
The link in the description for this GitHub repository points to https://tox-travis.readthedocs.io which then gets redirected to https://tox-travis.readthedocs.io/en/stable/

This documentation is pretty old, and still contains references to Python 2.6, e.g at the bottom of https://tox-travis.readthedocs.io/en/stable/contributing.html 

While this might be ok for a link at PyPi (as there it is bound to the release), I'd like the link here at the GitHub repository to link to the latest version of the documentation, e.g.
https://tox-travis.readthedocs.io/en/latest/ (which is more up to date).

**Comment by ryanhiebert** [comment]
Thanks for bringing it up. As a general rule, I don't think that pointing to the latest docs is wise. I see that you agree with that for PyPI, but not for GitHub, but my reasoning is the same for both: I don't want people to get to my documentation, and then find that they can't do something that they've found in the docs.

Your point that the documentation is getting a bit dated is well-taken though. I think it could make sense to create a new release for the purpose of updating the stable documentation link. Given my desire to only use links to stable documentation, does that seem like a wise course of action to you?

**Comment by jugmac00** [comment]
Hi Ryan,
thanks for getting back to me!

Your reasoning is absolutely reasonable :-)

From my point of view it is certainly not necessary to cut a release only to update the documentation.

I had a look at several other projects - and it looks like a 50/50 decision whether to link to stable or latest from GitHub - maybe I just spent most of my time at the latter projects :-)

I will close the ticket. Thanks again for your reply!

Best,
Jürgen
