### ISSUE TITLE
fold tox environments

### ISSUE THREAD

**Issue by graingert** [tox-dev/tox-travis#152]
eg https://github.com/abusalimov/pytest-travis-fold

spec here https://blog.travis-ci.com/2013-05-22-improving-build-visibility-log-folds/

**Comment by ryanhiebert** [comment]
Sounds like an interesting feature! I'm not sure exactly what I'd suggest for where the folds should be, but I'd be open to a pull request to look at.

**Comment by graingert** [comment]
@ryanhiebert the folds should be between environments
