### ISSUE TITLE
Question: any simple way to just run each tox environment in a separate jobs?

### ISSUE THREAD

**Issue by janLuke** [tox-dev/tox-travis#153]
Let's say I have the following tox environments:
```ini
[tox]
envlist =
    py{36,37,38}
    py39-django{17,18}
    lint
    mypy
```
I want to run each of them in a separate job. I know how to do it without using tox-travis ([here](https://github.com/click-contrib/click-help-colors/blob/master/.travis.yml) a random example) and I wonder if tox-travis makes it any easier.

**Comment by ryanhiebert** [comment]
If you're already setting TOXENV anyway, which is what tox-travis does internally, there may not be much that this library gets you.

**Comment by janLuke** [comment]
Ok, thank you.
