### ISSUE TITLE
Create docs

### ISSUE THREAD

**Issue by ryanhiebert** [tox-dev/tox-travis#37]
This project, while still simple to start using, has grown more features, and deserves some real docs with some better prose and layout.

**Comment by browniebroke** [comment]
I started using this and it's very nice, but I had to dig a bit into the code to get my beginner's answers.
I'm happy to bootstrap something that would include the current README, just let me know if you have any preference on the platform? Sphinx + readthedocs? Github pages? Other?

**Comment by ryanhiebert** [comment]
Sphinx + ReadTheDocs, in a `docs` directory at the top level. I probably have other opinions, but I'm not sure I can tell you what they are yet.

**Comment by ryanhiebert** [comment]
We've got Sphinx set up. We still need to write some better docs, and I need to set up ReadTheDocs. I'll set up ReadTheDocs when I release the next version.

**Comment by ryanhiebert** [comment]
Unfortunately, it looks like the `yaml` language is also not supported by PyPI. I've pushed a new version with just that change to the README. It should be on PyPI soon: 0.7.1.

**Comment by ryanhiebert** [comment]
And I was wrong. `yaml` is fine. I had another formatting error. Cutting release 0.7.2 to further immortalize my stupidity.
