### ISSUE TITLE
Strict Matching Mode

### ISSUE THREAD

**Issue by ryanhiebert** [tox-dev/tox-travis#58]
#55 was raised because a misconfiguration did something unexpected. When the misconfiguration caused the variant to not match any configuration, it surprisingly did what was _intended_, because when it ran all variants that matched, it turned out that only the one that was intended remained.

In the interest of not allowing errors to pass silently, we should introduce a strict matching option, so that if a variant is declared, present in the Travis environment, but not matched, it should raise an error instead of the likely case of running too many variants.

I think it's likely that we'll want to make this setting the default, but I'm not sure the best way to do that. For now, I'd like to just add this new mode with a setting (`strict = True`). I believe that rolling out this breaking change is likely to cause build errors that will be surprising because they'll be on pull requests that wouldn't have anything to do with Tox-Travis.

If and when we roll out that breaking change to the default behavior we should:

1. Make sure that we have a really good error message, that includes a link to the documentation describing the issue and the solution.
2. Add documentation directly describing this gotcha, and how to deal with it.
3. Add a prominent note to the README file, so that anyone coming to report the bug will see what they need to do to fix their build.

Note that this issue isn't about changing the default behavior, but simply about adding the strict mode. I just included the discussion about the possible default behavior change to note my thoughts on that possibility for future reference.

------------

Update: when we implement this, I do want to go ahead and make this a breaking change. That's going to be a bit more annoying, because there will be several issues that may bite a user and that we need to give quick access to documentation to fix their problem, but it's nice because I think it's just the way it should always work, and I don't really want to keep a flag for behavior that I don't think anyone should use anyway.

To that end, here's the list of breaking changes that this issue covers, taken from issues #55, #61, and #75:

* [ ] Throw an error if a configured variant doesn't match anything.
* [ ] Don't match envs that aren't configured in the tox.ini.
* [ ] Throw an error if no envs would be run.

**Comment by ryanhiebert** [comment]
#61, while working through the tests, brought up another edge condition that we may wish to change, and also may wish to make a part of this strict mode.

For backward compatibility reasons, and as introduced in the very first release of Tox-Travis, if you declare an environment, but no matching environments exist, the name will be used verbatim. This only happens in very limited cases, because it's all very squirrelly to manage.

I'm in favor of using strict mode to manage that feature as well.

**Comment by rpkilby** [comment]
Just a clarification.. "strict" mode should only apply when the `-e` option is provided or the `TOXENV` environment variable  is set. 

And as I [mentioned](https://github.com/ryanhiebert/tox-travis/issues/75#issuecomment-330867314) in #75, I'd argue that it's acceptable to go ahead and default to strict matching.

**Comment by ryanhiebert** [comment]
When either of those are given, they take complete priority over anything Tox-Travis does, so strict mode can't have anything to do with those.

Strict _Matching_ Mode is just a mode where we (1) never match envs that aren't in the `tox.ini` file, and (2) Ensure that if a declared Tox-Travis variant is not matched by some configuration, it throws an error.

If we think that it's reasonable to just do a breaking change to implement these and the strict form of #75, then I'd be inclined to do them all at once, and probably go ahead and release it as 1.0. What I don't want to do is require a user to keep coming back to us, to figure out what is wrong _this time_. We've got to figure out what we need to break, and break them all at once, with lots of documentation, warnings, and links to help them figure it out.

If they are caught by any of these breaking changes, it will _always_ be an interruption they had no way to expect would happen. I'm all for saving the user from himself, but we've also got to try to cause as little frustration as we can. Otherwise the best we'll be able to hope for is that they pin Tox-Travis to a particular version, and never be saved by our awesome improvements and bug fixes. And worse would be if they decided they couldn't trust us in their builds, and just stop using it altogether.

**Comment by rpkilby** [comment]
> When either of those are given, they take complete priority over anything Tox-Travis does, so strict mode can't have anything to do with those.

\*facepalm\* - I'll just chalk it up to having been a while since I last thought about this. 

I'm reversing my position on this - I don't think it make sense to change the default. There definitely are valid cases for multi-environment matching. Two examples that I am familiar with:

- [django-filter](https://github.com/carltongibson/django-filter/blob/645f24a9f24fbe7d080945a07c95383db00a619f/.travis.yml#L4-L9) leverages multiple-env matching. eg, CI jobs group envs by python version.
- [django-rest-framework](https://github.com/encode/django-rest-framework/blob/82c855c407a9607d77f5202f1eeb55d14311dc8d/.travis.yml#L3-L15) would use strict matching, as it targets one env per CI job.

**Comment by ryanhiebert** [comment]
You're closer, but I think you're still misunderstanding what strict mode does. The basic idea is that if a variant is defined, but the value of that variant doesn't match any configuration, we act as if no configuration was given at all for that variant in that run, which is just confusing. It should raise an error, because it's almost certainly a misconfiguration. Consider this example tox.ini and .travis.yml:

Note: this is _not_ a valid configuration, because as of the last time I knew, the Python `language` was not supported for `osx`.

```ini
[tox]
envlist = {linux,osx}-{spam,eggs}-py36

[travis]
os =
  linus: linux
  osx: osx
```

```yaml
language: python
os:
  - linux
  - osx
python:
  - 3.6
```

In this example, the user has misspelled `linux` in the Tox-Travis configuration. What the user intends to happen is for the `spam` and `eggs` envs for each os to be run. What will actually happen is that on `osx`, which is configured correctly, only the expected two will run, but on `linux` _all_ of the envs will run.

However, this is confusing behavior in the light of this misconfiguration. It would be better if it threw an error than if it ran everything, to alert the user to this misconfiguration.

Even with strict matching, multiple envs per job are supported, as demonstrated above. It's this type of misconfiguration that we're trying to disallow.

**Comment by rpkilby** [comment]
Just to recap, because I keep on misunderstanding this issue every time I try to reread it...

I incorrectly thought the proposed strict mode would require the factors to match *only* a single env. eg, you couldn't just provide `linux`, but instead would have to fully specify `linux-spam-py36`. This "fixes" the issue, because `linus` isn't a valid factor, and no single env would have been matched.

What is actually proposed is that the parsed CI environment factors *must* match variants defined in the tox-travis config. In your example, the tox.ini is misconfigured in that `linus` is not a valid os. The `linux` os factor will be parsed on Travis, but will not match `linus`, and an exception will be raised by tox-travis.

Hopefully I understand it this time 😄.

----

Additionally, #55 is the reverse of your example, and it's the .travis.yml instead that contains the typo.
```ini
[travis:env]
DJANGO =
    1.8: django18
```

```yml
matrix:
  include:
    - python: "3.3"
      env: DJANGO=1.18
```

The nice aspect of this strict matching is that it doesn't matter which file contains the typo.

**Comment by ryanhiebert** [comment]
Sounds like you've got it exactly right!

**Comment by ryanhiebert** [comment]
@rpkilby: I'm not sure if it's funny or not, but it made me laugh: I went back an re-read #55, and realized that it was you that made the issue in the first place. But I had totally forgotten that. :smile:
