### ISSUE TITLE
Unignoring outcomes should be configurable by testenv

### ISSUE THREAD

**Issue by rpkilby** [tox-dev/tox-travis#98]
`ignore_outcome` is configurable by section, and it would make sense for a section-specific `unignore_outcome` to complement it. Thoughts?

**Comment by ryanhiebert** [comment]
Makes sense to me, I was thinking the same thing when I was refactoring, but I wasn't sure it'd be a common use-case. My proposed implementation would be to make `True` a special-case that means all envs, and then make it an envlist, including expansion, of envs that should be un-ignored.
